import { test, expect } from '@playwright/test'
const ids=['istanbul-maiden-tower','istanbul-maiden-night','istanbul-galata','istanbul-bosphorus','istanbul-ortakoy','istanbul-rooftops','cappadocia','aegean-coast','paris-eiffel','tokyo-rain']
test('all scenes: decode, sound, favorites, settings, fullscreen, coffee, exit, resize',async({page})=>{
 test.setTimeout(180000)
 const errors:string[]=[];const bad:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errors.push(m.text())})
 page.on('response',r=>{if(r.status()>=400)bad.push(r.url())})
 for(const id of ids){
  await page.goto('/#/scene/'+id)
  await expect(page.locator('.viewer')).toHaveClass(/is-ready/)
  await expect(page.locator('.art-failed')).toHaveCount(0)
  await expect(page.locator('[data-testid="couple-layer"]')).toBeVisible()
  await expect(page.locator('.couple-base')).toHaveCount(1)
  expect(await page.locator('img').evaluateAll(imgs=>imgs.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true)
  await page.mouse.move(50,50)
  if(await page.getByRole('button',{name:'Ortam sesini aç',exact:true}).count())await page.getByRole('button',{name:'Ortam sesini aç',exact:true}).click()
  await expect(page.getByRole('button',{name:'Ortam sesini kapat',exact:true})).toBeVisible()
  await page.waitForTimeout(500)
  expect(await page.locator('.sound-caption').textContent()).not.toContain('yüklenemedi')
  const favorite=page.getByRole('button',{name:/Favoriye ekle|Favorilerden çıkar/})
  await favorite.click()
  await page.getByRole('button',{name:'Ayarlar',exact:true}).click()
  await page.getByLabel('Kalite',{exact:true}).selectOption('low')
  await expect(page.locator('.scene-art')).toHaveClass(/quality-low/)
  await page.getByLabel('Kalite',{exact:true}).selectOption('balanced')
  await page.getByRole('button',{name:'Ayarları kapat'}).click()
  await page.getByRole('button',{name:'Tam ekran',exact:true}).click()
  if(await page.evaluate(()=>Boolean(document.fullscreenElement)))await page.evaluate(()=>document.exitFullscreen())
  await page.getByRole('button',{name:'Kahve modu',exact:true}).click()
  await expect(page.locator('.viewer')).toHaveClass(/coffee-mode/)
  await page.mouse.click(200,150)
  await expect(page.locator('.viewer')).toHaveClass(/coffee-mode/)
  await page.getByRole('button',{name:'Kahve modundan çık'}).click()
  for(const [width,height] of [[1920,1080],[375,667],[390,844],[430,932],[667,375],[844,390],[932,430]]){
   await page.setViewportSize({width,height})
   expect(await page.evaluate(()=>({x:document.documentElement.scrollWidth-innerWidth,y:document.documentElement.scrollHeight-innerHeight}))).toEqual({x:0,y:0})
  }
  await page.mouse.move(100,110)
  await page.getByRole('button',{name:'Manzara değiştir'}).click()
  await expect(page.locator('.picker')).toBeVisible()
 }
 expect(errors).toEqual([]);expect(bad).toEqual([])
})
test('root opens the complete hero scene and picker stays secondary',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.viewer')).toHaveClass(/is-ready/)
 await expect(page.locator('[data-testid="couple-layer"]')).toBeVisible()
 await expect(page.locator('[data-testid="couple-layer"]')).toHaveAttribute('data-preset','hero')
 await expect(page.locator('.couple-base')).toHaveCount(1)
 await expect(page.locator('.water-shimmer')).toHaveCount(1)
 await expect(page.locator('.sprite-birds')).toHaveCount(1)
 await expect(page.locator('.sprite-ferry')).toHaveCount(1)
 await expect(page.locator('.cloud-layer')).toHaveCount(1)
 await page.waitForTimeout(3400)
 await expect(page.locator('.scene-ui')).toHaveCSS('opacity','0')
 await page.mouse.click(120,80)
 await page.getByRole('button',{name:'Manzara değiştir'}).click()
 await expect(page.locator('.picker')).toBeVisible()
})
test('visual viewport drives portrait, landscape and fullscreen layout transitions',async({page})=>{
 test.setTimeout(90000)
 const errors:string[]=[]
 page.on('pageerror',error=>errors.push(error.message))
 page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')errors.push(message.text())})
 const viewer=page.locator('.viewer')
 const expectViewport=async(width:number,height:number,landscape:boolean)=>{
  await expect(viewer).toHaveAttribute('data-viewport-width',String(width))
  await expect(viewer).toHaveAttribute('data-viewport-height',String(height))
  await expect(viewer).toHaveClass(landscape?/is-landscape/:/is-portrait/)
  if(landscape&&height<=600)await expect(viewer).toHaveClass(/is-compact-landscape/)
  const box=await viewer.boundingBox()
  expect(Math.round(box?.width??0)).toBe(width)
  expect(Math.round(box?.height??0)).toBe(height)
 }

 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await expect(viewer).toHaveClass(/is-ready/)
 await expectViewport(390,844,false)
 await page.setViewportSize({width:844,height:390})
 await expectViewport(844,390,true)

 await page.setViewportSize({width:430,height:932})
 await expectViewport(430,932,false)
 await page.setViewportSize({width:932,height:430})
 await expectViewport(932,430,true)
 await page.setViewportSize({width:375,height:667})
 await expectViewport(375,667,false)
 await page.setViewportSize({width:667,height:375})
 await expectViewport(667,375,true)

 await page.setViewportSize({width:390,height:844})
 await page.reload()
 await expect(viewer).toHaveClass(/is-ready/)
 await page.getByRole('button',{name:'Tam ekran',exact:true}).click()
 await expect(viewer).toHaveAttribute('data-fullscreen','true')
 await page.setViewportSize({width:844,height:390})
 await expectViewport(844,390,true)
 if(await page.evaluate(()=>Boolean(document.fullscreenElement)))await page.evaluate(()=>document.exitFullscreen())
 else await page.getByRole('button',{name:'Tam ekran',exact:true}).click()
 await expect(viewer).toHaveAttribute('data-fullscreen','false')
 await page.setViewportSize({width:390,height:844})
 await expectViewport(390,844,false)
 await page.setViewportSize({width:844,height:390})
 await expectViewport(844,390,true)
 expect(errors).toEqual([])
})
test('immersive fallback stays responsive when native fullscreen is unavailable',async({page})=>{
 const errors:string[]=[]
 page.on('pageerror',error=>errors.push(error.message))
 page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')errors.push(message.text())})
 await page.addInitScript(()=>Object.defineProperty(HTMLElement.prototype,'requestFullscreen',{value:undefined,configurable:true}))
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 const viewer=page.locator('.viewer')
 await expect(viewer).toHaveClass(/is-ready/)
 await page.getByRole('button',{name:'Tam ekran',exact:true}).click()
 await expect(viewer).toHaveClass(/is-immersive/)
 await expect(viewer).toHaveAttribute('data-fullscreen','true')
 await page.setViewportSize({width:844,height:390})
 await expect(viewer).toHaveClass(/is-landscape/)
 await expect(viewer).toHaveAttribute('data-viewport-width','844')
 await expect(viewer).toHaveAttribute('data-viewport-height','390')
 await page.getByRole('button',{name:'Tam ekran',exact:true}).click()
 await expect(viewer).not.toHaveClass(/is-immersive/)
 await expect(viewer).toHaveAttribute('data-fullscreen','false')
 expect(errors).toEqual([])
})
test('autohide, persisted favorites, private view, invalid storage and no autoplay',async({page})=>{
 const audioRequests:string[]=[];page.on('request',r=>{if(r.url().includes('/audio/'))audioRequests.push(r.url())})
 await page.goto('/#/view/istanbul-maiden-tower')
 await expect(page.locator('.viewer')).toHaveClass(/is-ready/)
 expect(audioRequests).toHaveLength(0)
 await page.waitForTimeout(4700)
 await expect(page.locator('.scene-ui')).toHaveCSS('opacity','0')
 await page.mouse.click(200,100)
 await expect(page.locator('.scene-ui')).toHaveClass(/is-visible/)
 await page.getByRole('button',{name:'Favoriye ekle'}).click()
 await page.reload()
 await expect(page.getByRole('button',{name:'Favorilerden çıkar'})).toBeVisible()
 await expect(page.locator('.personal-message')).toContainText('Bunu görünce')
 await page.goto('/#/view/paris-eiffel?message=')
 await expect(page.locator('.viewer')).toHaveClass(/is-ready/)
 await expect(page.locator('.personal-message')).toHaveCount(0)
 await page.evaluate(()=>{localStorage.setItem('pencere:favorites','{}');localStorage.setItem('pencere:recent','null')})
 await page.reload();await expect(page.locator('.viewer')).toBeVisible()
})
